export type { DiscDetailIdentity } from "./discs/detail/domain/discDetail";
export type { CommentDisc } from "./discs/domain/commentDisc";
export type { DiscListItem } from "./discs/listing/application/discListPort";
export type { ArtistDetailIdentity } from "./artists/detail/domain/artistDetail";
export type { CalendarDisc, CalendarGroup } from "./discs/calendars/domain/discCalendar";
export type { ArtistManagementItem, ArtistManagementDisc, ArtistManagementMatch } from "./artists/domain/artistManagement";
export type { LastFmManagementDependencies } from "./artists/discovery/application/artistExternalProfile";
export { default as DiscCalendarView } from "./discs/calendars/presentation/views/DiscCalendarView.vue";
export { default as BabyDiscCalendarView } from "./discs/calendars/presentation/views/BabyDiscCalendarView.vue";
export { exportCalendarHtml } from "./discs/calendars/application/calendarTools";
export type { Catalog, Country, Genre } from "./reference-data/domain/catalog";
export { useCatalogStore } from "./reference-data/presentation/stores/catalogStore.ts";
export type { UpdateArtistInput } from "./artists/application/artistManagementPort";
export { alternateCalendarCountryId } from "./artists/editing/domain/calendarCountry";
export { useArtistManagementList } from "./artists/listing/presentation/composables/useArtistManagementList.ts";
export { applyArtistEditLocally } from "./artists/editing/presentation/composables/artistManagementEditing.ts";
export { confirmAndDeleteArtist, removeArtistLocally } from "./artists/deletion/presentation/composables/artistManagementDeletion.ts";
export { default as LastFmManagementModal } from "./artists/discovery/presentation/components/LastFmManagementModal.vue";
export { useLastFmManagement } from "./artists/discovery/presentation/composables/useLastFmManagement.ts";
